services:
  postgres:
    restart: always
    image: postgres
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    restart: always
    image: adminer:latest
    depends_on:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080